# Generated by Django 4.2.24 on 2025-09-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название')),
                ('chat_id', models.BigIntegerField(db_index=True, help_text='ID канала/группы (например, -1001234567890).', verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, help_text='Напр.: my_channel (без @)', max_length=150, null=True, verbose_name='Username без @')),
                ('invite_link', models.URLField(blank=True, help_text='Если приватный канал/чат.', null=True, verbose_name='Пригласительная ссылка')),
                ('is_group', models.BooleanField(default=False, verbose_name='Это группа/чат')),
                ('is_required', models.BooleanField(default=True, verbose_name='Обязательная подписка')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Канал/группа для подписки',
                'verbose_name_plural': 'Каналы/группы для подписки',
                'ordering': ('sort_order', 'title'),
            },
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_blocked',
            field=models.BooleanField(default=False, help_text='Заблокировал ли пользователь бота', verbose_name='Заблокирован'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_premium',
            field=models.BooleanField(default=False, help_text='Есть ли у пользователя Telegram Premium', verbose_name='Премиум'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='is_subscribed',
            field=models.BooleanField(default=True, help_text='Состоит ли пользователь в обязательном канале', verbose_name='Подписан'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='language_code',
            field=models.CharField(blank=True, help_text='Код языка, который передаёт Telegram (например, ru, en)', max_length=12, null=True, verbose_name='Язык интерфейса'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='tg_id',
            field=models.BigIntegerField(db_index=True, help_text='Уникальный идентификатор пользователя в Telegram', unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='telegramuser',
            name='username',
            field=models.CharField(blank=True, help_text='@username, если установлен', max_length=150, null=True, verbose_name='Username'),
        ),
    ]
