# Generated by Django 4.2.24 on 2025-09-22 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptionchannel_alter_telegramuser_created_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='telegramuser',
            name='is_subscribed',
        ),
    ]
