# Generated by Django 5.2.6 on 2025-09-29 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_telegramadmin_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
