# Generated by Django 5.2.6 on 2025-09-29 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_telegramadmin_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, unique=True, verbose_name='Telegram ID'),
        ),
    ]
