# Generated by Django 5.2.6 on 2025-09-29 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_telegramadmin_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='telegramadmin',
            name='telegram_id',
            field=models.BigIntegerField(db_index=True, help_text='Уникальный идентификатор администратора в Telegram (@raw_data_bot)', unique=True, verbose_name='Telegram ID'),
        ),
    ]
