# Generated by Django 5.2.6 on 2025-09-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_cartitem_tg_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfoPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(choices=[('about', 'О нас'), ('reviews', 'Отзывы клиентов'), ('warranty', 'Гарантия'), ('returns', 'Возврат'), ('delivery', 'Доставка'), ('tg_channel', 'Наш Telegram канал')], db_index=True, help_text='Системный ключ раздела', max_length=50, unique=True)),
                ('title', models.CharField(max_length=120)),
                ('telegraph_url', models.URLField(blank=True, null=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('body', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Инфо-страница',
                'verbose_name_plural': 'Инфо-страницы',
                'ordering': ('sort_order', 'title'),
            },
        ),
    ]
