# Generated by Django 4.2.24 on 2025-09-22 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_infopage'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Категория, на которую ведёт баннер', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banners', to='shop.category', verbose_name='Категория'),
        ),
    ]
