# Generated by Django 4.2.24 on 2025-09-22 08:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_subscriptionchannel_alter_telegramuser_created_at_and_more'),
        ('shop', '0004_banner_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(max_length=160, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='banner',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='shop.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='tg_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='users.telegramuser', verbose_name='Telegram пользователь'),
        ),
        migrations.AlterField(
            model_name='cartitem',
            name='user_id',
            field=models.CharField(max_length=64, verbose_name='Telegram ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=120, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='shop.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='body',
            field=models.TextField(blank=True, null=True, verbose_name='Текстовый контент'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=models.CharField(choices=[('about', 'О нас'), ('reviews', 'Отзывы клиентов'), ('warranty', 'Гарантия'), ('returns', 'Возврат'), ('delivery', 'Доставка'), ('tg_channel', 'Наш Telegram канал')], db_index=True, help_text='Системный ключ раздела', max_length=50, unique=True, verbose_name='Ключ раздела'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='telegraph_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на статью (Telegraph)'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='title',
            field=models.CharField(max_length=120, verbose_name='Заголовок'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='shop.category', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=160, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='label',
            field=models.CharField(max_length=40, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='price_delta',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Наценка к цене'),
        ),
        migrations.AlterField(
            model_name='productsize',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='shop.product', verbose_name='Продукт'),
        ),
    ]
