# Generated by Django 5.2.6 on 2025-09-23 06:02

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_alter_banner_image_alter_banner_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infopage',
            name='body',
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='external_url',
        ),
        migrations.RemoveField(
            model_name='infopage',
            name='telegraph_url',
        ),
        migrations.AddField(
            model_name='infopage',
            name='content',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Контент'),
        ),
    ]
