# Generated by Django 5.2.6 on 2025-09-23 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_infopage_body_remove_infopage_external_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='external_url',
            field=models.URLField(blank=True, null=True, verbose_name='Внешняя ссылка'),
        ),
    ]
