# Generated by Django 5.2.6 on 2025-09-23 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_infopage_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infopage',
            name='external_url',
            field=models.URLField(blank=True, help_text='Внешняя ссылка на страницу', null=True, verbose_name='Внешняя ссылка'),
        ),
        migrations.AlterField(
            model_name='infopage',
            name='slug',
            field=models.CharField(choices=[('about', 'О нас'), ('reviews', 'Отзывы клиентов'), ('warranty', 'Гарантия'), ('delivery', 'Доставка')], db_index=True, help_text='Системный ключ раздела', max_length=50, unique=True, verbose_name='Ключ раздела'),
        ),
    ]
