# Generated by Django 5.2.6 on 2025-09-26 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_alter_infopage_external_url_alter_infopage_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productsize',
            name='price_delta',
        ),
    ]
