# Generated by Django 5.2.6 on 2025-09-29 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_remove_order_note'),
        ('users', '0007_alter_telegramadmin_telegram_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='tg_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='users.telegramuser', verbose_name='TG пользователь'),
            preserve_default=False,
        ),
    ]
