# Generated by Django 5.2.6 on 2025-09-30 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_order_user_id_order_tg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infopage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='info_pages/', verbose_name='Изображение'),
        ),
    ]
