# Generated by Django 5.2.6 on 2025-10-14 15:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_banner_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, help_text='Обязателен для СДЭК и Почты России', null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_type',
            field=models.CharField(choices=[('cdek', 'СДЭК'), ('post_ru', 'Почта России'), ('meet', 'Личная встреча')], default=django.utils.timezone.now, max_length=20, verbose_name='Тип доставки'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='full_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=160, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=django.utils.timezone.now, max_length=32, verbose_name='Телефон'),
            preserve_default=False,
        ),
    ]
