# Generated by Django 5.2.6 on 2025-10-17 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0018_order_delivery_address_order_delivery_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_file',
            field=models.FileField(blank=True, help_text='Если загружаешь файл — ссылку можно не указывать.', null=True, upload_to='products/videos/', verbose_name='Файл видео'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_poster',
            field=models.ImageField(blank=True, help_text='Картинка-заставка (опционально).', null=True, upload_to='products/videos/', verbose_name='Постер видео'),
        ),
        migrations.AddField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Можно указать внешнюю ссылку на видео.', null=True, verbose_name='Ссылка на видео (YouTube/Telegram и т.п.)'),
        ),
    ]
