# Generated by Django 5.2.6 on 2025-10-17 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0019_product_video_file_product_video_poster_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminPaymentProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=80, null=True, verbose_name='Название профиля')),
                ('bank_name', models.CharField(max_length=120, verbose_name='Банк')),
                ('card_number', models.CharField(max_length=64, verbose_name='Номер карты/счёта')),
                ('card_holder', models.CharField(max_length=120, verbose_name='Держатель карты')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Платёжный профиль',
                'verbose_name_plural': 'Платёжные профили',
                'ordering': ('-is_active', 'sort_order', 'id'),
            },
        ),
        migrations.AddField(
            model_name='order',
            name='pay_bank',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Банк'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_card',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Номер карты/счёта'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_holder',
            field=models.CharField(blank=True, max_length=120, null=True, verbose_name='Держатель карты'),
        ),
        migrations.AlterField(
            model_name='product',
            name='video_url',
            field=models.URLField(blank=True, help_text='Можно указать внешнюю ссылку на видео.', null=True, verbose_name='Ссылка на видео (YouTube/Вконтакте и т.п.)'),
        ),
        migrations.AddField(
            model_name='order',
            name='pay_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='shop.adminpaymentprofile', verbose_name='Платёжный профиль (источник)'),
        ),
    ]
